services:
  amethyst:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amethyst-container
    image: amethyst-image
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped