CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    iv VARBINARY(16) NOT NULL,

    discord_id VARCHAR(20) NOT NULL UNIQUE,
    discord_username VARCHAR(32) NOT NULL,

    roblox_id BIGINT UNSIGNED UNIQUE,
    roblox_username VARCHAR(20),

    settings JSON NOT NULL DEFAULT '{}',
    fflags JSON NOT NULL DEFAULT '{}',

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);