blank_issues_enabled: false
contact_links:
    - name: Discord Server
      url: https://discord.gg/gGwCcCXxrX
      about: Please submit your questions here. Join our community for in-depth discussions and to easily contact Amethyst developers.
