CREATE TABLE IF NOT EXISTS api_keys (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `version` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    
    guild_id BIGINT UNSIGNED NOT NULL,

    `name` VARCHAR(20) NOT NULL,
    `value` VARCHAR(100) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT TRUE,
    permissions JSON NOT NULL DEFAULT '[]',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NOT NULL,

    FOREIGN KEY (guild_id) REFERENCES guild_profiles(id),
    FOREIGN KEY (created_by) REFERENCES user_profiles(id)
);

CREATE TRIGGER IF NOT EXISTS trigger_ApiKeys_BeforeUpdate
BEFORE UPDATE ON api_keys
FOR EACH ROW
BEGIN
    SET NEW.version = OLD.version + 1;
END;
