CREATE TABLE IF NOT EXISTS APIKeys (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    __v INT UNSIGNED NOT NULL DEFAULT 1,
    
    guildId VARCHAR(20) NOT NULL,

    `name` VARCHAR(20) NOT NULL,
    `value` VARCHAR(100) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT TRUE,
    permissions JSON NOT NULL DEFAULT '[]',

    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdBy VARCHAR(20) NOT NULL,

    FOREIGN KEY (guildId) REFERENCES GuildProfiles(id),
    FOREIGN KEY (createdBy) REFERENCES UserProfiles(id)
);

CREATE TRIGGER IF NOT EXISTS trigger_APIKeys_BeforeUpdate
BEFORE UPDATE ON APIKeys
FOR EACH ROW
BEGIN
    SET NEW.__v = OLD.__v + 1;
END;
