CREATE TABLE IF NOT EXISTS guild_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `version` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    encryption_iv VARBINARY(16) NOT NULL,
    
    shortname VARCHAR(10) NOT NULL UNIQUE,

    guild_id VARCHAR(20) NOT NULL,
    `name` VARCHAR(100) NOT NULL,

    permissions JSON NOT NULL DEFAULT '{}',
    channels JSON NOT NULL DEFAULT '{}',

    settings JSON NOT NULL DEFAULT '{}',
    fflags JSON NOT NULL DEFAULT '{}',

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS trigger_GuildProfiles_BeforeUpdate
BEFORE UPDATE ON guild_profiles
FOR EACH ROW
BEGIN
    SET NEW.version = OLD.version + 1;
END;
