CREATE TABLE IF NOT EXISTS user_profiles (
    _id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    __v BIGINT UNSIGNED NOT NULL DEFAULT 0,

    discord_id BIGINT UNSIGNED UNIQUE,
    roblox_id BIGINT UNSIGNED UNIQUE,
    roblox_username VARCHAR(20) UNIQUE,

    settings JSON NOT NULL DEFAULT '{}',
    fflags JSON NOT NULL DEFAULT '{}'
);

CREATE TRIGGER IF NOT EXISTS trigger_UserProfiles_BeforeUpdate
BEFORE UPDATE ON user_profiles
FOR EACH ROW
BEGIN
    SET NEW.__v = OLD.__v + 1;
END;
